version = 2
clobber = true
keep = 3

[[items]]
destination = "$XDG_CONFIG_HOME/alacritty/alacritty.toml"
source = "alacritty.toml.mustache"
render = true

[[items]]
source = "bat-config"
destination = "$XDG_CONFIG_HOME/bat/config"
hook = "bat cache --build"

[[items]]
source = "codex.toml"
destination = "$HOME/.codex/config.toml"

[[items]]
destination = "$XDG_STATE_HOME/nix-theme/interface.dconf"
source = "dconf.mustache"
hook = "if [ -n \"${DBUS_SESSION_BUS_ADDRESS:-}\" ]; then dconf load /org/gnome/desktop/interface/ < $XDG_STATE_HOME/nix-theme/interface.dconf; else dbus-run-session -- dconf load /org/gnome/desktop/interface/ < $XDG_STATE_HOME/nix-theme/interface.dconf; fi"
render = true

[[items]]
destination = "$XDG_CONFIG_HOME/gh/hosts.yaml"
source = "gh-hosts.yaml.mustache"
render = true

[[items]]
destination = "$XDG_CONFIG_HOME/git/config"
source = "gitconfig.mustache"
render = true

[[items]]
destination = "$XDG_CONFIG_HOME/gtk-3.0/bookmarks"
source = "gtk3-bookmarks.mustache"
render = true

[[items]]
destination = "$XDG_CONFIG_HOME/gtk-3.0/settings.ini"
source = "gtk3-settings.ini.mustache"
render = true

[[items]]
destination = "$XDG_CONFIG_HOME/gtk-4.0/gtk-dark.css"
source = "gtk4-dark.css.mustache"
render = true

[[items]]
destination = "$XDG_CONFIG_HOME/gtk-4.0/gtk.css"
source = "gtk4.css.mustache"
render = true

[[items]]
destination = "$XDG_CONFIG_HOME/gtk-4.0/settings.ini"
source = "gtk4-settings.ini.mustache"
render = true

[[items]]
source = "hidden-files"
destination = "$HOME/.hidden"

[[items]]
source = "neovim.lua"
destination = "$XDG_CONFIG_HOME/nvim/init.lua"

[[items]]
source = "neovim-options.lua"
destination = "$XDG_CONFIG_HOME/nvim/lua/config/options.lua"

[[items]]
source = "neovim-plugin.lua"
destination = "$XDG_CONFIG_HOME/nvim/lua/plugins/init.lua"

[[items]]
destination = "$XDG_DATA_HOME/noctalia/plugins/sysdash/init.luau"
source = "noctalia-plugin-sysmon/init.luau"

[[items]]
destination = "$XDG_DATA_HOME/noctalia/plugins/sysdash/plugin.toml"
source = "noctalia-plugin-sysmon/plugin.toml"

[[items]]
destination = "$XDG_CONFIG_HOME/noctalia/config.toml"
source = "noctalia-config.toml.mustache"
render = true

[[items]]
source = "starship-config.toml"
destination = "$XDG_CONFIG_HOME/starship.toml"

[[items]]
destination = "$XDG_CONFIG_HOME/umbriel/config.toml"
source = "umbriel-config.toml.mustache"
render = true

[[items]]
destination = "$XDG_CONFIG_HOME/vesktop/settings/quickCss.css"
source = "vencord.css.mustache"
render = true

[[items]]
destination = "$XDG_STATE_HOME/nix-theme/vscode-noctalia-template.json"
source = "vscode-noctalia-template.json"

[[items]]
destination = "$XDG_CONFIG_HOME/Code/User/settings.json"
source = "vscode-settings.json.mustache"
render = true

[[items]]
destination = "$XDG_CONFIG_HOME/zathura/zathurarc"
source = "zathurarc.mustache"
render = true
