version = 1
clobber = true

[[items]]
destination = "$XDG_CONFIG_HOME/alacritty/alacritty.toml"
template = "alacritty.toml"
themed = true

[[items]]
destination = "$XDG_CONFIG_HOME/bat/themes/Base16.tmTheme"
template = "bat-base16.tmTheme"
themed = true

[[items]]
source = "bat-config"
destination = "$XDG_CONFIG_HOME/bat/config"

[[items]]
source = "gh-config.yaml"
destination = "$XDG_CONFIG_HOME/gh/config.yaml"

[[items]]
destination = "$XDG_CONFIG_HOME/gh/hosts.yaml"
template = "gh-hosts.yaml"

[[items]]
destination = "$XDG_CONFIG_HOME/git/config"
template = "gitconfig"

[[items]]
destination = "$XDG_CONFIG_HOME/gtk-3.0/settings.ini"
template = "gtk3-settings.ini"
themed = true

[[items]]
destination = "$XDG_CONFIG_HOME/gtk-4.0/gtk-dark.css"
template = "gtk4-dark.css"

[[items]]
destination = "$XDG_CONFIG_HOME/gtk-4.0/gtk.css"
template = "gtk4.css"

[[items]]
destination = "$XDG_CONFIG_HOME/gtk-4.0/settings.ini"
template = "gtk4-settings.ini"
themed = true

[[items]]
source = "hidden-files"
destination = "$HOME/.hidden"

[[items]]
destination = "$XDG_CONFIG_HOME/noctalia/config.toml"
template = "noctalia-config.toml"
themed = true

[[items]]
destination = "$XDG_CONFIG_HOME/qt5ct/qt5ct.conf"
template = "qt5ct.conf"
themed = true

[[items]]
destination = "$XDG_CONFIG_HOME/qt6ct/qt6ct.conf"
template = "qt6ct.conf"
themed = true

[[items]]
source = "starship-config.toml"
destination = "$XDG_CONFIG_HOME/starship.toml"

[[items]]
destination = "$XDG_CONFIG_HOME/umbriel/config.toml"
template = "umbriel-config.toml"
themed = true

[[items]]
destination = "$XDG_CONFIG_HOME/vesktop/settings/quickCss.css"
template = "vencord.css"
themed = true

[[items]]
source = "vencord-settings.json"
destination = "$XDG_CONFIG_HOME/vesktop/settings/settings.json"

[[items]]
source = "vesktop-settings.json"
destination = "$XDG_CONFIG_HOME/vesktop/settings.json"

[[items]]
destination = "$XDG_CONFIG_HOME/Code/User/settings.json"
template = "vscode-settings.json"

[[items]]
destination = "$XDG_CONFIG_HOME/zathura/zathurarc"
template = "zathurarc"
themed = true
